name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build
      run: npm run build
    - name: Checkout API Server
      uses: actions/checkout@v4
      with:
        repository: MikeJerred/points-api-server
        path: points-api-server
    - name: Run Playwright tests
      env:
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
        POSTGRES_URL_NO_SSL: ${{ secrets.POSTGRES_URL_NO_SSL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      run: |
        cd points-api-server && npm ci && npm start &
        npx wait-on tcp:8080 && npm test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
